簡轉繁

diff --git a/service/server_status_client_centos b/service/server_status_client_centos
--- a/service/server_status_client_centos
+++ b/service/server_status_client_centos
@@ -20,8 +20,8 @@ if [[ -e "/usr/local/ServerStatus/client/status-client.py" ]]; then
 elif [[ -e "/usr/local/ServerStatus/status-client.py" ]]; then
 	BIN="/usr/local/ServerStatus/status-client.py"
 else
-	echo -e "${Error_font_prefix}[错误]${Font_suffix} 客户端文件($NAME_BIN)找不到 !" && exit 1
 fi
+	echo -e "${Error_font_prefix}[錯誤]${Font_suffix} 客戶端文件($NAME_BIN)找不到 !" && exit 1
 RETVAL=0
 
 check_running(){
@@ -34,15 +34,15 @@ check_running(){
 }
 do_start(){
 	if check_running; then
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..." && exit 0
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME (PID ${PID}) 正在執行..." && exit 0
 	else
 		ulimit -n 51200 >/dev/null 2>&1
 		nohup python -u "$BIN" > /tmp/serverstatus_client.log 2>&1 &
 		sleep 2s
 		if check_running; then
-			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 启动成功 !"
+			echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 啟動成功 !"
 		else
-			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAME 启动失败 !"
+			echo -e "${Error_font_prefix}[錯誤]${Font_suffix} $NAME 啟動失敗 !"
 		fi
 	fi
 }
@@ -51,20 +51,20 @@ do_stop(){
 		kill -9 "${PID}"
 		RETVAL=$?
 		if [[ $RETVAL -eq 0 ]]; then
-			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 停止成功 !"
+			echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 停止成功 !"
 		else
-			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAME 停止失败 !"
+			echo -e "${Error_font_prefix}[錯誤]${Font_suffix} $NAME 停止失敗 !"
 		fi
 	else
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行"
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 未執行"
 		RETVAL=1
 	fi
 }
 do_status(){
 	if check_running; then
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..."
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME (PID ${PID}) 正在執行..."
 	else
-		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
+		echo -e "${Info_font_prefix}[訊息]${Font_suffix} $NAME 未執行 !"
 		RETVAL=1
 	fi
 }
